compatibility_date = "2026-01-12"

compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "XSIC_DB"
database_name = "xsic-prod"
database_id = "5b673bff-546c-461c-a410-3ef1c2acf0c4"

[[kv_namespaces]]
binding = "XSIC_CACHE"
id = "f924cee770124033804fc510fc6e5633"
